# -*- coding: utf-8 -*-
"""bloodmnist_dcgan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1we5LCXTyZb0K-CHHcXzFgRLXko3iRvSm
"""

!pip install medmnist torch torchvision matplotlib numpy tqdm scikit-learn pytorch-fid -q

import os
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from collections import Counter

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Subset

import torchvision.transforms as transforms
from torchvision.utils import make_grid, save_image

import medmnist
from medmnist import INFO

torch.manual_seed(42)
np.random.seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

os.makedirs("bloodmnist_outputs", exist_ok=True)
os.makedirs("bloodmnist_outputs/generated_epochs", exist_ok=True)

data_flag = 'bloodmnist'
info = INFO[data_flag]

print("Dataset info")
print("Task:", info['task'])
print("Number of channels:", info['n_channels'])
print("Labels:", info['label'])

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

DataClass = getattr(medmnist, info['python_class'])

train_dataset = DataClass(split='train', transform=transform, download=True)
test_dataset = DataClass(split='test', transform=transform, download=True)

print("Train size:", len(train_dataset))
print("Test size:", len(test_dataset))

batch_size = 128

train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

images, labels = next(iter(train_loader))

print("Image batch shape:", images.shape)
print("Label batch shape:", labels.shape)
print("Pixel min:", images.min().item())
print("Pixel max:", images.max().item())

sample_images, sample_labels = next(iter(train_loader))

fig, axes = plt.subplots(3, 4, figsize=(10, 8))
axes = axes.flatten()

for i in range(12):
    img = denormalize(sample_images[i]).permute(1, 2, 0).numpy()
    label = sample_labels[i].item()
    axes[i].imshow(img)
    axes[i].set_title(f"Class: {label}")
    axes[i].axis("off")

plt.tight_layout()
plt.savefig("bloodmnist_outputs/sample_real_images.png", dpi=300, bbox_inches="tight")
plt.show()

all_labels = []

for _, labels in train_loader:
    all_labels.extend(labels.squeeze().tolist())

label_counts = Counter(all_labels)

print("Class distribution:")
for k, v in sorted(label_counts.items()):
    print(f"Class {int(k)}: {v}")

classes = list(sorted(label_counts.keys()))
counts = [label_counts[c] for c in classes]

plt.figure(figsize=(8, 5))
plt.bar(classes, counts)
plt.title("BloodMNIST Class Distribution")
plt.xlabel("Class")
plt.ylabel("Count")
plt.grid(axis='y', alpha=0.3)
plt.savefig("bloodmnist_outputs/class_distribution.png", dpi=300, bbox_inches="tight")
plt.show()

class Generator(nn.Module):
    def __init__(self, latent_dim=100, img_channels=3):
        super().__init__()
        self.init_size = 7
        self.fc = nn.Linear(latent_dim, 128 * self.init_size * self.init_size)

        self.conv_blocks = nn.Sequential(
            nn.BatchNorm2d(128),

            nn.Upsample(scale_factor=2),  # 7 -> 14
            nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(True),

            nn.Upsample(scale_factor=2),  # 14 -> 28
            nn.Conv2d(128, 64, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(True),

            nn.Conv2d(64, img_channels, kernel_size=3, stride=1, padding=1),
            nn.Tanh()
        )

    def forward(self, z):
        out = self.fc(z)
        out = out.view(out.size(0), 128, self.init_size, self.init_size)
        img = self.conv_blocks(out)
        return img

class Discriminator(nn.Module):
    def __init__(self, img_channels=3):
        super().__init__()

        def block(in_filters, out_filters, use_bn=True):
            layers = [
                nn.Conv2d(in_filters, out_filters, kernel_size=3, stride=2, padding=1),
                nn.LeakyReLU(0.2, inplace=True),
                nn.Dropout2d(0.25)
            ]
            if use_bn:
                layers.append(nn.BatchNorm2d(out_filters))
            return layers

        self.model = nn.Sequential(
            *block(img_channels, 16, use_bn=False),  # 28 -> 14
            *block(16, 32),                          # 14 -> 7
            *block(32, 64),                          # 7 -> 4
            *block(64, 128)                          # 4 -> 2
        )

        self.adv_layer = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 2 * 2, 1),
            nn.Sigmoid()
        )

    def forward(self, img):
        features = self.model(img)
        validity = self.adv_layer(features)
        return validity

latent_dim = 100

G = Generator(latent_dim=latent_dim, img_channels=3).to(device)
D = Discriminator(img_channels=3).to(device)

z = torch.randn(16, latent_dim).to(device)
fake_test = G(z)
print("Generator output shape:", fake_test.shape)

disc_test = D(fake_test)
print("Discriminator output shape:", disc_test.shape)

def save_generated_grid(generator, latent_dim, epoch, output_dir, device, n_images=64, nrow=8):
    generator.eval()
    with torch.no_grad():
        z = torch.randn(n_images, latent_dim, device=device)
        fake_imgs = generator(z).cpu()
        fake_imgs = denormalize(fake_imgs)
        grid = make_grid(fake_imgs, nrow=nrow)
        save_image(grid, os.path.join(output_dir, f"epoch_{epoch}.png"))
    generator.train()

def train_dcgan(
    train_loader,
    latent_dim=100,
    lr=0.0002,
    epochs=10,
    sample_interval=1,
    run_name="default_run"
):
    generator = Generator(latent_dim=latent_dim, img_channels=3).to(device)
    discriminator = Discriminator(img_channels=3).to(device)

    criterion = nn.BCELoss()

    optimizer_G = optim.Adam(generator.parameters(), lr=lr, betas=(0.5, 0.999))
    optimizer_D = optim.Adam(discriminator.parameters(), lr=lr, betas=(0.5, 0.999))

    g_losses = []
    d_losses = []

    run_dir = os.path.join("bloodmnist_outputs", run_name)
    os.makedirs(run_dir, exist_ok=True)
    epoch_img_dir = os.path.join(run_dir, "generated_epochs")
    os.makedirs(epoch_img_dir, exist_ok=True)

    print(f"\nStarting run: {run_name}")
    print(f"Learning rate: {lr}, Epochs: {epochs}")

    for epoch in range(epochs):
        epoch_g_loss = 0.0
        epoch_d_loss = 0.0

        for real_imgs, _ in tqdm(train_loader, desc=f"{run_name} | Epoch {epoch+1}/{epochs}", leave=False):
            real_imgs = real_imgs.to(device, non_blocking=True)
            batch_size_curr = real_imgs.size(0)

            real_labels = torch.ones(batch_size_curr, 1, device=device)
            fake_labels = torch.zeros(batch_size_curr, 1, device=device)

            # ---------------------
            # Train Discriminator
            # ---------------------
            optimizer_D.zero_grad()

            real_output = discriminator(real_imgs)
            d_real_loss = criterion(real_output, real_labels)

            z = torch.randn(batch_size_curr, latent_dim, device=device)
            fake_imgs = generator(z)
            fake_output = discriminator(fake_imgs.detach())
            d_fake_loss = criterion(fake_output, fake_labels)

            d_loss = d_real_loss + d_fake_loss
            d_loss.backward()
            optimizer_D.step()

            # -----------------
            # Train Generator
            # -----------------
            optimizer_G.zero_grad()

            z = torch.randn(batch_size_curr, latent_dim, device=device)
            gen_imgs = generator(z)
            output = discriminator(gen_imgs)

            g_loss = criterion(output, real_labels)
            g_loss.backward()
            optimizer_G.step()

            epoch_d_loss += d_loss.item()
            epoch_g_loss += g_loss.item()

        avg_d_loss = epoch_d_loss / len(train_loader)
        avg_g_loss = epoch_g_loss / len(train_loader)

        d_losses.append(avg_d_loss)
        g_losses.append(avg_g_loss)

        print(f"Epoch [{epoch+1}/{epochs}] | D Loss: {avg_d_loss:.4f} | G Loss: {avg_g_loss:.4f}")

        if (epoch + 1) % sample_interval == 0:
            save_generated_grid(generator, latent_dim, epoch + 1, epoch_img_dir, device)

    # Save final models
    torch.save(generator.state_dict(), os.path.join(run_dir, "generator.pth"))
    torch.save(discriminator.state_dict(), os.path.join(run_dir, "discriminator.pth"))

    return generator, discriminator, g_losses, d_losses, run_dir

def plot_losses(g_losses, d_losses, save_path=None, title="DCGAN Training Losses"):
    plt.figure(figsize=(8, 5))
    plt.plot(g_losses, label="Generator Loss")
    plt.plot(d_losses, label="Discriminator Loss")
    plt.title(title)
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True)
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.show()

real_batch, _ = next(iter(train_loader))
real_batch = denormalize(real_batch[:64])

real_grid = make_grid(real_batch, nrow=8)

plt.figure(figsize=(10, 10))
plt.imshow(real_grid.permute(1, 2, 0))
plt.title("Real BloodMNIST Images")
plt.axis("off")
plt.savefig("bloodmnist_outputs/real_images_grid.png", dpi=300, bbox_inches="tight")
plt.show()

subset_size = 3000
train_subset = Subset(train_dataset, range(subset_size))

train_loader_tune = DataLoader(
    train_subset,
    batch_size=128,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

print("Tuning subset size:", len(train_subset))

G_tune_1, D_tune_1, g_losses_1, d_losses_1, run_dir_1 = train_dcgan(
    train_loader=train_loader_tune,
    latent_dim=100,
    lr=0.0002,
    epochs=5,
    sample_interval=1,
    run_name="tuning_lr_0002"
)

plot_losses(
    g_losses_1,
    d_losses_1,
    save_path=os.path.join(run_dir_1, "losses.png"),
    title="Tuning Run 1 - lr=0.0002"
)

G_tune_2, D_tune_2, g_losses_2, d_losses_2, run_dir_2 = train_dcgan(
    train_loader=train_loader_tune,
    latent_dim=100,
    lr=0.0001,
    epochs=5,
    sample_interval=1,
    run_name="tuning_lr_0001"
)

plot_losses(
    g_losses_2,
    d_losses_2,
    save_path=os.path.join(run_dir_2, "losses.png"),
    title="Tuning Run 2 - lr=0.0001"
)

def show_generated_images(generator, latent_dim=100, n_images=64, nrow=8, save_path=None, title="Generated Images"):
    generator.eval()
    with torch.no_grad():
        z = torch.randn(n_images, latent_dim, device=device)
        fake_imgs = generator(z).cpu()
        fake_imgs = denormalize(fake_imgs)

    grid = make_grid(fake_imgs, nrow=nrow)

    plt.figure(figsize=(10, 10))
    plt.imshow(grid.permute(1, 2, 0))
    plt.title(title)
    plt.axis("off")
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.show()

show_generated_images(
    G_tune_1,
    save_path=os.path.join(run_dir_1, "generated_final.png"),
    title="Tuning Run 1 - Generated Images"
)

show_generated_images(
    G_tune_2,
    save_path=os.path.join(run_dir_2, "generated_final.png"),
    title="Tuning Run 2 - Generated Images"
)

final_batch_size = 128

train_loader_final = DataLoader(
    train_dataset,
    batch_size=final_batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

G_final, D_final, g_losses_final, d_losses_final, final_run_dir = train_dcgan(
    train_loader=train_loader_final,
    latent_dim=100,
    lr=0.0002,
    epochs=10,
    sample_interval=1,
    run_name="final_full_run"
)

plot_losses(
    g_losses_final,
    d_losses_final,
    save_path=os.path.join(final_run_dir, "final_losses.png"),
    title="Final BloodMNIST DCGAN Training Losses"
)

show_generated_images(
    G_final,
    save_path=os.path.join(final_run_dir, "generated_final.png"),
    title="Final Generated BloodMNIST Images"
)

real_batch, _ = next(iter(train_loader_final))
real_batch = denormalize(real_batch[:64])
real_grid = make_grid(real_batch, nrow=8)

plt.figure(figsize=(10, 10))
plt.imshow(real_grid.permute(1, 2, 0))
plt.title("Real BloodMNIST Images")
plt.axis("off")
plt.savefig(os.path.join(final_run_dir, "real_grid.png"), dpi=300, bbox_inches="tight")
plt.show()

show_generated_images(
    G_final,
    save_path=os.path.join(final_run_dir, "fake_grid.png"),
    title="Generated BloodMNIST Images"
)

"""**FID for BloodMNIST**

*Saving real and fake images into folders for FID*
"""

import os
from torchvision.utils import save_image

real_fid_dir = os.path.join(final_run_dir, "fid_real")
fake_fid_dir = os.path.join(final_run_dir, "fid_fake")

os.makedirs(real_fid_dir, exist_ok=True)
os.makedirs(fake_fid_dir, exist_ok=True)

print(real_fid_dir)
print(fake_fid_dir)

"""*Save real images*"""

max_real_images = 1000
saved_count = 0

for imgs, _ in train_loader_final:
    imgs = denormalize(imgs)  # back to [0,1]

    for img in imgs:
        save_path = os.path.join(real_fid_dir, f"real_{saved_count:04d}.png")
        save_image(img, save_path)

        saved_count += 1
        if saved_count >= max_real_images:
            break

    if saved_count >= max_real_images:
        break

print("Saved real images:", saved_count)

#saving fake images
G_final.eval()

num_fake_images = 1000
batch_gen = 128
saved_count = 0

with torch.no_grad():
    while saved_count < num_fake_images:
        curr_batch = min(batch_gen, num_fake_images - saved_count)
        z = torch.randn(curr_batch, latent_dim, device=device)
        fake_imgs = G_final(z).cpu()
        fake_imgs = denormalize(fake_imgs)

        for img in fake_imgs:
            save_path = os.path.join(fake_fid_dir, f"fake_{saved_count:04d}.png")
            save_image(img, save_path)
            saved_count += 1

print("Saved fake images:", saved_count)

!python -m pytorch_fid "{real_fid_dir}" "{fake_fid_dir}"

bloodmnist_fid = 85.43  # replace with your actual output
print("BloodMNIST FID:", bloodmnist_fid)

with open(os.path.join(final_run_dir, "fid_result.txt"), "w") as f:
    f.write(f"BloodMNIST FID: {bloodmnist_fid}\n")

print("FID result saved.")