# -*- coding: utf-8 -*-
"""cicids_tabular_gan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WPiGKmpieulncZzHXOJ0QSFYLatXmLU
"""

!pip install pandas numpy matplotlib scikit-learn torch tqdm seaborn -q

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from collections import Counter

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

torch.manual_seed(42)
np.random.seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

os.makedirs("cicids_outputs", exist_ok=True)

csv_path = "/content/Wednesday-workingHours.pcap_ISCX.csv"
df = pd.read_csv(csv_path)
print(df.shape)
df.head()

print("Columns:")
print(df.columns.tolist())

print("\nLabel counts:")
print(df.iloc[:, -1].value_counts())

label_col = df.columns[-1]
print("Label column:", label_col)

df[label_col] = df[label_col].astype(str).str.strip()

keep_mask = (
    df[label_col].str.upper().eq("BENIGN") |
    df[label_col].str.contains("DoS", case=False, na=False)
)

df_filtered = df[keep_mask].copy()

print("Filtered shape:", df_filtered.shape)
print(df_filtered[label_col].value_counts())

df_filtered["binary_label"] = df_filtered[label_col].apply(
    lambda x: "BENIGN" if str(x).upper() == "BENIGN" else "DoS"
)

print(df_filtered["binary_label"].value_counts())

class_counts = df_filtered["binary_label"].value_counts()

plt.figure(figsize=(6, 4))
plt.bar(class_counts.index, class_counts.values)
plt.title("Class Balance: BENIGN vs DoS")
plt.xlabel("Class")
plt.ylabel("Count")
plt.grid(axis="y", alpha=0.3)
plt.savefig("cicids_outputs/class_balance.png", dpi=300, bbox_inches="tight")
plt.show()

# Separate features and labels
X = df_filtered.drop(columns=[label_col, "binary_label"]).copy()
y = df_filtered["binary_label"].copy()

# Convert all feature columns to numeric where possible
for col in X.columns:
    X[col] = pd.to_numeric(X[col], errors="coerce")

# Replace inf with NaN
X.replace([np.inf, -np.inf], np.nan, inplace=True)

# Check missing values
print("Missing values before cleaning:", X.isna().sum().sum())

# Drop columns that are completely missing
X = X.dropna(axis=1, how="all")

# Fill remaining NaNs with column median
X = X.fillna(X.median(numeric_only=True))

print("Missing values after cleaning:", X.isna().sum().sum())
print("Feature shape after cleaning:", X.shape)

nunique = X.nunique()
constant_cols = nunique[nunique <= 1].index.tolist()

print("Constant columns removed:", len(constant_cols))
X = X.drop(columns=constant_cols)

print("Feature shape after dropping constants:", X.shape)

max_rows = 20000

if len(X) > max_rows:
    sampled_idx = np.random.choice(len(X), max_rows, replace=False)
    X = X.iloc[sampled_idx].reset_index(drop=True)
    y = y.iloc[sampled_idx].reset_index(drop=True)

print("Final sampled shape:", X.shape)
print(y.value_counts())

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Scaled shape:", X_scaled.shape)

X_tensor = torch.tensor(X_scaled, dtype=torch.float32)
dataset = TensorDataset(X_tensor)

batch_size = 128

train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
input_dim = X_tensor.shape[1]

print("Input dimension:", input_dim)

pca = PCA(n_components=2)
X_pca_real = pca.fit_transform(X_scaled)

plt.figure(figsize=(7, 6))
colors = np.where(y.values == "BENIGN", "blue", "red")

plt.scatter(X_pca_real[:, 0], X_pca_real[:, 1], c=colors, alpha=0.4, s=8)
plt.title("PCA of Real CICIDS Samples")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.grid(True)
plt.savefig("cicids_outputs/pca_real_data.png", dpi=300, bbox_inches="tight")
plt.show()

class Generator(nn.Module):
    def __init__(self, latent_dim, output_dim):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim)
        )

    def forward(self, z):
        return self.model(z)

class Discriminator(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.LeakyReLU(0.2),
            nn.Dropout(0.3),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

latent_dim = 32
lr = 0.0002
epochs = 50

G = Generator(latent_dim, input_dim).to(device)
D = Discriminator(input_dim).to(device)

criterion = nn.BCELoss()

optimizer_G = optim.Adam(G.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_D = optim.Adam(D.parameters(), lr=lr, betas=(0.5, 0.999))

z = torch.randn(16, latent_dim).to(device)
fake_test = G(z)
print("Generator output shape:", fake_test.shape)

disc_test = D(fake_test)
print("Discriminator output shape:", disc_test.shape)

g_losses = []
d_losses = []

for epoch in range(epochs):
    epoch_g_loss = 0.0
    epoch_d_loss = 0.0

    for real_batch in tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}", leave=False):
        real_data = real_batch[0].to(device)
        batch_size_curr = real_data.size(0)

        real_labels = torch.ones(batch_size_curr, 1, device=device)
        fake_labels = torch.zeros(batch_size_curr, 1, device=device)

        # ---------------------
        # Train Discriminator
        # ---------------------
        optimizer_D.zero_grad()

        real_output = D(real_data)
        d_real_loss = criterion(real_output, real_labels)

        z = torch.randn(batch_size_curr, latent_dim, device=device)
        fake_data = G(z)
        fake_output = D(fake_data.detach())
        d_fake_loss = criterion(fake_output, fake_labels)

        d_loss = d_real_loss + d_fake_loss
        d_loss.backward()
        optimizer_D.step()

        # -----------------
        # Train Generator
        # -----------------
        optimizer_G.zero_grad()

        z = torch.randn(batch_size_curr, latent_dim, device=device)
        gen_data = G(z)
        output = D(gen_data)

        g_loss = criterion(output, real_labels)
        g_loss.backward()
        optimizer_G.step()

        epoch_d_loss += d_loss.item()
        epoch_g_loss += g_loss.item()

    avg_d_loss = epoch_d_loss / len(train_loader)
    avg_g_loss = epoch_g_loss / len(train_loader)

    d_losses.append(avg_d_loss)
    g_losses.append(avg_g_loss)

    print(f"Epoch [{epoch+1}/{epochs}] | D Loss: {avg_d_loss:.4f} | G Loss: {avg_g_loss:.4f}")

plt.figure(figsize=(8, 5))
plt.plot(g_losses, label="Generator Loss")
plt.plot(d_losses, label="Discriminator Loss")
plt.title("CICIDS Tabular GAN Training Losses")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.savefig("cicids_outputs/cicids_gan_losses.png", dpi=300, bbox_inches="tight")
plt.show()

G.eval()

with torch.no_grad():
    z = torch.randn(len(X_scaled), latent_dim).to(device)
    X_fake = G(z).cpu().numpy()

print("Generated fake shape:", X_fake.shape)

pca = PCA(n_components=2)
X_real_pca = pca.fit_transform(X_scaled)
X_fake_pca = pca.transform(X_fake)

plt.figure(figsize=(8, 6))
plt.scatter(X_real_pca[:, 0], X_real_pca[:, 1], alpha=0.3, s=8, label="Real")
plt.scatter(X_fake_pca[:, 0], X_fake_pca[:, 1], alpha=0.3, s=8, label="Generated")
plt.title("PCA: Real vs Generated CICIDS Feature Vectors")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend()
plt.grid(True)
plt.savefig("cicids_outputs/pca_real_vs_generated.png", dpi=300, bbox_inches="tight")
plt.show()

selected_features = X.columns[:4].tolist()
print("Selected features for histogram comparison:", selected_features)

X_fake_df = pd.DataFrame(X_fake, columns=X.columns)

for feature in selected_features:
    plt.figure(figsize=(7, 4))
    plt.hist(X_scaled[:, X.columns.get_loc(feature)], bins=50, alpha=0.5, label="Real", density=True)
    plt.hist(X_fake_df[feature], bins=50, alpha=0.5, label="Generated", density=True)
    plt.title(f"Distribution Comparison: {feature}")
    plt.xlabel(feature)
    plt.ylabel("Density")
    plt.legend()
    plt.grid(True)
    plt.savefig(f"cicids_outputs/hist_{feature}.png", dpi=300, bbox_inches="tight")
    plt.show()

real_means = pd.DataFrame(X_scaled, columns=X.columns).mean()
fake_means = X_fake_df.mean()

comparison_df = pd.DataFrame({
    "Real Mean": real_means,
    "Generated Mean": fake_means
})

comparison_df.head(10)

comparison_df.to_csv("cicids_outputs/mean_comparison.csv", index=True)