# -*- coding: utf-8 -*-
"""full_numpy_bitmap_pizza.npy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThWqdOm1P4ChXFo3XTiKYEihQ0Vzq_KE
"""

!pip install numpy matplotlib torch torchvision tqdm scikit-learn pillow pytorch-fid -q

import os
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, random_split

from torchvision.utils import make_grid, save_image

torch.manual_seed(42)
np.random.seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

os.makedirs("quickdraw_outputs", exist_ok=True)
os.makedirs("quickdraw_outputs/generated_epochs", exist_ok=True)

!wget https://storage.googleapis.com/quickdraw_dataset/full/numpy_bitmap/pizza.npy

pizza_data = np.load("pizza.npy")
print("Original shape:", pizza_data.shape)

pizza_data = pizza_data.reshape(-1, 28, 28)
print("Reshaped shape:", pizza_data.shape)

fig, axes = plt.subplots(3, 4, figsize=(8, 8))
axes = axes.flatten()

for i in range(12):
    axes[i].imshow(pizza_data[i], cmap="gray")
    axes[i].axis("off")

plt.suptitle("Real QuickDraw Pizza Sketches", y=0.92)
plt.tight_layout()
plt.savefig("real_sample_sketches.png", dpi=300, bbox_inches="tight")
plt.show()

max_samples = 10000

if len(pizza_data) > max_samples:
    idx = np.random.choice(len(pizza_data), max_samples, replace=False)
    pizza_data = pizza_data[idx]

print("Using samples:", pizza_data.shape[0])

pizza_data = pizza_data.astype(np.float32) / 255.0
pizza_data = (pizza_data - 0.5) / 0.5

print("Min:", pizza_data.min(), "Max:", pizza_data.max())

pizza_data = np.expand_dims(pizza_data, axis=1)   # shape: (N, 1, 28, 28)

pizza_tensor = torch.tensor(pizza_data, dtype=torch.float32)
dataset = TensorDataset(pizza_tensor)

batch_size = 128
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

print("Tensor shape:", pizza_tensor.shape)

def denormalize(img_tensor):
    return img_tensor * 0.5 + 0.5

class Generator(nn.Module):
    def __init__(self, latent_dim=100, img_channels=1):
        super().__init__()
        self.init_size = 7
        self.fc = nn.Linear(latent_dim, 128 * self.init_size * self.init_size)

        self.conv_blocks = nn.Sequential(
            nn.BatchNorm2d(128),

            nn.Upsample(scale_factor=2),  # 7 -> 14
            nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(True),

            nn.Upsample(scale_factor=2),  # 14 -> 28
            nn.Conv2d(128, 64, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(True),

            nn.Conv2d(64, img_channels, kernel_size=3, stride=1, padding=1),
            nn.Tanh()
        )

    def forward(self, z):
        out = self.fc(z)
        out = out.view(out.size(0), 128, self.init_size, self.init_size)
        img = self.conv_blocks(out)
        return img

class Discriminator(nn.Module):
    def __init__(self, img_channels=1):
        super().__init__()

        def block(in_filters, out_filters, use_bn=True):
            layers = [
                nn.Conv2d(in_filters, out_filters, kernel_size=3, stride=2, padding=1),
                nn.LeakyReLU(0.2, inplace=True),
                nn.Dropout2d(0.25)
            ]
            if use_bn:
                layers.append(nn.BatchNorm2d(out_filters))
            return layers

        self.model = nn.Sequential(
            *block(img_channels, 16, use_bn=False),  # 28 -> 14
            *block(16, 32),                          # 14 -> 7
            *block(32, 64),                          # 7 -> 4
            *block(64, 128)                          # 4 -> 2
        )

        self.adv_layer = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128 * 2 * 2, 1),
            nn.Sigmoid()
        )

    def forward(self, img):
        features = self.model(img)
        validity = self.adv_layer(features)
        return validity

latent_dim = 100
lr = 0.0002
epochs = 10

G = Generator(latent_dim=latent_dim, img_channels=1).to(device)
D = Discriminator(img_channels=1).to(device)

criterion = nn.BCELoss()

optimizer_G = optim.Adam(G.parameters(), lr=lr, betas=(0.5, 0.999))
optimizer_D = optim.Adam(D.parameters(), lr=lr, betas=(0.5, 0.999))

z = torch.randn(16, latent_dim).to(device)
fake_test = G(z)
print("Generator output shape:", fake_test.shape)

disc_test = D(fake_test)
print("Discriminator output shape:", disc_test.shape)

def save_generated_grid(generator, latent_dim, epoch, output_dir, device, n_images=64, nrow=8):
    generator.eval()
    with torch.no_grad():
        z = torch.randn(n_images, latent_dim, device=device)
        fake_imgs = generator(z).cpu()
        fake_imgs = denormalize(fake_imgs)
        grid = make_grid(fake_imgs, nrow=nrow, normalize=False)
        save_image(grid, os.path.join(output_dir, f"epoch_{epoch}.png"))
    generator.train()

g_losses = []
d_losses = []
sample_interval = 2

for epoch in range(epochs):
    epoch_g_loss = 0.0
    epoch_d_loss = 0.0

    for real_batch in tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}", leave=False):
        real_imgs = real_batch[0].to(device)
        batch_size_curr = real_imgs.size(0)

        real_labels = torch.ones(batch_size_curr, 1, device=device)
        fake_labels = torch.zeros(batch_size_curr, 1, device=device)

        # Train Discriminator
        optimizer_D.zero_grad()

        real_output = D(real_imgs)
        d_real_loss = criterion(real_output, real_labels)

        z = torch.randn(batch_size_curr, latent_dim, device=device)
        fake_imgs = G(z)
        fake_output = D(fake_imgs.detach())
        d_fake_loss = criterion(fake_output, fake_labels)

        d_loss = d_real_loss + d_fake_loss
        d_loss.backward()
        optimizer_D.step()

        # Train Generator
        optimizer_G.zero_grad()

        z = torch.randn(batch_size_curr, latent_dim, device=device)
        gen_imgs = G(z)
        output = D(gen_imgs)

        g_loss = criterion(output, real_labels)
        g_loss.backward()
        optimizer_G.step()

        epoch_d_loss += d_loss.item()
        epoch_g_loss += g_loss.item()

    avg_d_loss = epoch_d_loss / len(train_loader)
    avg_g_loss = epoch_g_loss / len(train_loader)

    d_losses.append(avg_d_loss)
    g_losses.append(avg_g_loss)

    print(f"Epoch [{epoch+1}/{epochs}] | D Loss: {avg_d_loss:.4f} | G Loss: {avg_g_loss:.4f}")

    if (epoch + 1) % sample_interval == 0:
        save_generated_grid(G, latent_dim, epoch + 1, "quickdraw_outputs/generated_epochs", device)

plt.figure(figsize=(8, 5))
plt.plot(g_losses, label="Generator Loss")
plt.plot(d_losses, label="Discriminator Loss")
plt.title("QuickDraw Pizza DCGAN Training Losses")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.savefig("quickdraw_outputs/quickdraw_dcgan_losses.png", dpi=300, bbox_inches="tight")
plt.show()

G.eval()
with torch.no_grad():
    z = torch.randn(64, latent_dim, device=device)
    generated_imgs = G(z).cpu()
    generated_imgs = denormalize(generated_imgs)

grid = make_grid(generated_imgs, nrow=8)

plt.figure(figsize=(10, 10))
plt.imshow(grid.permute(1, 2, 0).squeeze(), cmap="gray")
plt.title("Generated QuickDraw Pizza Sketches")
plt.axis("off")
plt.savefig("quickdraw_outputs/generated_pizza_sketches.png", dpi=300, bbox_inches="tight")
plt.show()

real_batch = next(iter(train_loader))[0][:64]
real_batch = denormalize(real_batch)

real_grid = make_grid(real_batch, nrow=8)

plt.figure(figsize=(10, 10))
plt.imshow(real_grid.permute(1, 2, 0).squeeze(), cmap="gray")
plt.title("Real QuickDraw Pizza Sketches")
plt.axis("off")
plt.savefig("quickdraw_outputs/real_pizza_sketches_grid.png", dpi=300, bbox_inches="tight")
plt.show()

real_fid_dir = "quickdraw_outputs/fid_real"
fake_fid_dir = "quickdraw_outputs/fid_fake"

os.makedirs(real_fid_dir, exist_ok=True)
os.makedirs(fake_fid_dir, exist_ok=True)

max_real_images = 1000
saved_count = 0

for img_tensor in pizza_tensor[:max_real_images]:
    img = denormalize(img_tensor)
    save_image(img, os.path.join(real_fid_dir, f"real_{saved_count:04d}.png"))
    saved_count += 1

print("Saved real images:", saved_count)

num_fake_images = 1000
batch_gen = 128
saved_count = 0

G.eval()
with torch.no_grad():
    while saved_count < num_fake_images:
        curr_batch = min(batch_gen, num_fake_images - saved_count)
        z = torch.randn(curr_batch, latent_dim, device=device)
        fake_imgs = G(z).cpu()
        fake_imgs = denormalize(fake_imgs)

        for img in fake_imgs:
            save_image(img, os.path.join(fake_fid_dir, f"fake_{saved_count:04d}.png"))
            saved_count += 1

print("Saved fake images:", saved_count)

!python -m pytorch_fid "{real_fid_dir}" "{fake_fid_dir}"

quickdraw_fid = 0.0
print("QuickDraw Pizza FID:", quickdraw_fid)

pizza_data = np.load("pizza.npy")
pizza_data = pizza_data.reshape(-1, 28, 28)