# -*- coding: utf-8 -*-
"""part1_gan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OHY1jeJ4POHhJJBZsJ1rP0ZXFs_Dc-4
"""

!pip install torch torchvision matplotlib numpy tqdm -q

import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

def generate_sine_data(n_samples=2000):
    x = np.random.uniform(-np.pi, np.pi, n_samples)
    y = np.sin(x)
    data = np.column_stack((x, y))
    return data.astype(np.float32)

sine_data = generate_sine_data(2000)
print("Shape:", sine_data.shape)

plt.figure(figsize=(6, 6))
plt.scatter(sine_data[:, 0], sine_data[:, 1], alpha=0.5, s=10)
plt.title("Real Sine-Wave Data")
plt.xlabel("x")
plt.ylabel("y = sin(x)")
plt.grid(True)
plt.show()

batch_size = 128

sine_tensor = torch.tensor(sine_data)
sine_dataset = TensorDataset(sine_tensor)
sine_loader = DataLoader(sine_dataset, batch_size=batch_size, shuffle=True)

class Generator(nn.Module):
    def __init__(self, latent_dim=5):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 2)
        )

    def forward(self, z):
        return self.model(z)

class Discriminator(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(2, 64),
            nn.LeakyReLU(0.2),
            nn.Linear(64, 32),
            nn.LeakyReLU(0.2),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

latent_dim = 5
lr = 0.001
epochs = 1000

G = Generator(latent_dim).to(device)
D = Discriminator().to(device)

criterion = nn.BCELoss()

optimizer_G = optim.Adam(G.parameters(), lr=lr)
optimizer_D = optim.Adam(D.parameters(), lr=lr)

g_losses = []
d_losses = []

for epoch in tqdm(range(epochs)):
    epoch_g_loss = 0.0
    epoch_d_loss = 0.0

    for real_batch in sine_loader:
        real_data = real_batch[0].to(device)
        batch_size_curr = real_data.size(0)

        # Labels
        real_labels = torch.ones(batch_size_curr, 1).to(device)
        fake_labels = torch.zeros(batch_size_curr, 1).to(device)

        # Train Discriminator
        optimizer_D.zero_grad()

        # Real data loss
        real_output = D(real_data)
        d_loss_real = criterion(real_output, real_labels)

        # Fake data loss
        z = torch.randn(batch_size_curr, latent_dim).to(device)
        fake_data = G(z)
        fake_output = D(fake_data.detach())
        d_loss_fake = criterion(fake_output, fake_labels)

        d_loss = d_loss_real + d_loss_fake
        d_loss.backward()
        optimizer_D.step()

        # Train Generator
        optimizer_G.zero_grad()

        z = torch.randn(batch_size_curr, latent_dim).to(device)
        generated_data = G(z)
        output = D(generated_data)

        g_loss = criterion(output, real_labels)
        g_loss.backward()
        optimizer_G.step()

        epoch_d_loss += d_loss.item()
        epoch_g_loss += g_loss.item()

    d_losses.append(epoch_d_loss / len(sine_loader))
    g_losses.append(epoch_g_loss / len(sine_loader))

    if (epoch + 1) % 200 == 0:
        print(f"Epoch [{epoch+1}/{epochs}] | D Loss: {d_losses[-1]:.4f} | G Loss: {g_losses[-1]:.4f}")

plt.figure(figsize=(8, 5))
plt.plot(g_losses, label="Generator Loss")
plt.plot(d_losses, label="Discriminator Loss")
plt.title("GAN Training Losses - Sine Wave")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

G.eval()

with torch.no_grad():
    z = torch.randn(2000, latent_dim).to(device)
    fake_samples = G(z).cpu().numpy()

plt.figure(figsize=(7, 7))
plt.scatter(sine_data[:, 0], sine_data[:, 1], alpha=0.4, s=10, label="Real")
plt.scatter(fake_samples[:, 0], fake_samples[:, 1], alpha=0.4, s=10, label="Generated")
plt.title("Real vs Generated Samples - Sine Wave GAN")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(7, 7))
plt.scatter(sine_data[:, 0], sine_data[:, 1], alpha=0.4, s=10, label="Real")
plt.scatter(fake_samples[:, 0], fake_samples[:, 1], alpha=0.4, s=10, label="Generated")
plt.title("Real vs Generated Samples - Sine Wave GAN")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.grid(True)
plt.savefig("sine_real_vs_generated.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(g_losses, label="Generator Loss")
plt.plot(d_losses, label="Discriminator Loss")
plt.title("GAN Training Losses - Sine Wave")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.savefig("sine_gan_losses.png", dpi=300, bbox_inches="tight")
plt.show()

def generate_gaussian_mixture(n_samples=2000):
    centers = [
        (-2, -2),
        (2, -2),
        (-2, 2),
        (2, 2)
    ]

    data = []
    for _ in range(n_samples):
        cx, cy = centers[np.random.randint(0, len(centers))]
        x = np.random.normal(cx, 0.3)
        y = np.random.normal(cy, 0.3)
        data.append([x, y])

    return np.array(data, dtype=np.float32)


gaussian_data = generate_gaussian_mixture(2000)

plt.figure(figsize=(6, 6))
plt.scatter(gaussian_data[:, 0], gaussian_data[:, 1], s=10, alpha=0.5)
plt.title("Real Gaussian Mixture Data")
plt.grid(True)
plt.show()

gaussian_tensor = torch.tensor(gaussian_data)
gaussian_dataset = TensorDataset(gaussian_tensor)
gaussian_loader = DataLoader(gaussian_dataset, batch_size=128, shuffle=True)

g_losses = []
d_losses = []

for epoch in tqdm(range(epochs)):
    epoch_g_loss = 0.0
    epoch_d_loss = 0.0

    for real_batch in gaussian_loader:
        real_data = real_batch[0].to(device)
        batch_size_curr = real_data.size(0)

        # Labels
        real_labels = torch.ones(batch_size_curr, 1).to(device)
        fake_labels = torch.zeros(batch_size_curr, 1).to(device)

        # Train Discriminator
        optimizer_D.zero_grad()

        # Real data loss
        real_output = D(real_data)
        d_loss_real = criterion(real_output, real_labels)

        # Fake data loss
        z = torch.randn(batch_size_curr, latent_dim).to(device)
        fake_data = G(z)
        fake_output = D(fake_data.detach())
        d_loss_fake = criterion(fake_output, fake_labels)

        d_loss = d_loss_real + d_loss_fake
        d_loss.backward()
        optimizer_D.step()

        # Train Generator
        optimizer_G.zero_grad()

        z = torch.randn(batch_size_curr, latent_dim).to(device)
        generated_data = G(z)
        output = D(generated_data)

        g_loss = criterion(output, real_labels)
        g_loss.backward()
        optimizer_G.step()

        epoch_d_loss += d_loss.item()
        epoch_g_loss += g_loss.item()

    d_losses.append(epoch_d_loss / len(sine_loader))
    g_losses.append(epoch_g_loss / len(sine_loader))

    if (epoch + 1) % 200 == 0:
        print(f"Epoch [{epoch+1}/{epochs}] | D Loss: {d_losses[-1]:.4f} | G Loss: {g_losses[-1]:.4f}")

G.eval()

with torch.no_grad():
    z = torch.randn(2000, latent_dim).to(device)
    fake_samples = G(z).cpu().numpy()

plt.figure(figsize=(6, 6))
plt.scatter(gaussian_data[:, 0], gaussian_data[:, 1], s=10, alpha=0.4, label="Real")
plt.scatter(fake_samples[:, 0], fake_samples[:, 1], s=10, alpha=0.4, label="Generated")
plt.legend()
plt.title("Gaussian Mixture: Real vs Generated")
plt.grid(True)
plt.savefig("Gaussian Mixture: Real vs Generated.png", dpi=300, bbox_inches="tight")
plt.show()

